name: 'OpenAPI Discourse Upload Action'
description:
  'Uploads an OpenAPI specification to a Discourse topic for rendering using
  https://github.com/wwerner/discourse-rapidoc-theme-component'
author: 'wwerner'

branding:
  icon: 'file'
  color: 'green'

# Define your inputs here.
inputs:
  spec_file:
    description: 'The OAS file to add code samples to'
    required: true
  out_file:
    description: 'Where to store the augmented OAS JSON'
    required: true
  languages:
    description:
      'Comma-separated list of languages for which to generate code samples.
      Defaults to "go, python, shell, java, kotlin, swift"'
    required: false

runs:
  using: node20
  main: dist/index.js
