openapi: 3.0.0
info:
  title: Solution API
  description: >-
    The user-centered Solution API makes it possible to build customised energy
    applications.
  version: 2.0.0
  license:
    name: All rights reserved.
    url: https://www.gridx.ai/
  x-api-id: ba9d6a25-ae1a-4ac8-af7a-70b76db17021
  x-audience: company-internal
servers:
  - url: https://api.gridx.de
tags:
  - name: Scan Configuration
    x-displayName: Scan Configuration
  - name: Account
    x-displayName: Account
  - name: Market Prices
    x-displayName: Market Prices
  - name: Token
    x-displayName: Token
  - name: System
    x-displayName: System
  - name: Policy
    x-displayName: Policy
  - name: Document
    x-displayName: Document
  - name: Group
    x-displayName: Group
  - name: User
    x-displayName: User
  - name: Notification
    x-displayName: Notification
  - name: Plan
    x-displayName: Plan
  - name: RFIDTag
    x-displayName: RFIDTag
  - name: Platform
    x-displayName: Platform
  - name: Energy Tariff
    x-displayName: Energy Tariff
  - name: Asset
    x-displayName: Asset
  - name: Clusters
    x-displayName: Clusters
  - name: Customer
    x-displayName: Customer
  - name: Import Power Limit
    x-displayName: Import Power Limit
  - name: Appliance
    x-displayName: Appliance
  - name: EV Charging Schedule
    x-displayName: EV Charging Schedule
  - name: EV Configuration
    x-displayName: EV Configuration
  - name: EV Profile
    x-displayName: EV Profile
  - name: Battery Control Command
    x-displayName: Battery Control Command
  - name: Capacity Tariff
    x-displayName: Capacity Tariff
  - name: Gateway
    x-displayName: Gateway
  - name: Scan
    x-displayName: Scan
  - name: Job
    x-displayName: Job
  - name: TariffV2
    x-displayName: TariffV2
  - name: TimeOfUse
    x-displayName: TimeOfUse
  - name: GridSignals
    x-displayName: GridSignals
  - name: Power Limit Schedule
    x-displayName: Power Limit Schedule
  - name: EMS
    x-displayName: EMS
  - name: Cluster
    x-displayName: Cluster
  - name: Product Functionality
    x-displayName: Product Functionality
  - name: Product Option
    x-displayName: Product Option
  - name: Devices
    x-displayName: Devices
  - name: Power Sequence
    x-displayName: Power Sequence
  - name: Star
    x-displayName: Star
paths:
  /accounts/{accountID}/scanconfiguration:
    get:
      summary: Retrieve Scan Configuration
      tags:
        - Scan Configuration
      security:
        - BearerAuth:
            - ScanConfigurationRead
    post:
      summary: Create a Scan Configuration
      tags:
        - Scan Configuration
      security:
        - BearerAuth:
            - ScanConfigurationWrite
    patch:
      summary: Update a Scan Configuration
      tags:
        - Scan Configuration
      security:
        - BearerAuth:
            - ScanConfigurationWrite
    delete:
      summary: Delete a Scan Configuration
      tags:
        - Scan Configuration
      security:
        - BearerAuth:
            - ScanConfigurationWrite
  /account:
    get:
      summary: Retrieve the authenticated Account
      description: Get the account that is currently logged in.
      tags:
        - Account
      security:
        - BearerAuth:
            - AccountRead
    patch:
      summary: Update the authenticated Account
      description: Update the user data of the authenticated account.
      tags:
        - Account
      security:
        - BearerAuth:
            - AccountWrite
  /account/market-prices/{platform}:
    get:
      summary: Retrieve energy market prices for the authenticated account
      deprecated: true
      description: >
        List energy market prices for the given interval. Prices are fetched
        from an external energy market

        platform.

        For the given interval, the hourly prices of the second to last day and
        for the last day are returned in a 60M resolution.

        For all the other days in the interval, the average daily price is
        returned.

        For example, in order to get hourly prices for the current day and the
        day before, set the **end** of the interval to the current day.


        **Deprecated** - Use `/systems/{systemID}/tariff/prices` instead.
      tags:
        - Market Prices
      security:
        - BearerAuth:
            - MarketPricesRead
  /account/tokens:
    get:
      summary: Get API tokens
      description: >-
        Retrieve all the organizational API tokens for the currently
        authenticated account.
      tags:
        - Token
      security:
        - BearerAuth:
            - GetAPITokens
    post:
      summary: Create an organizational API token
      tags:
        - Token
      security:
        - BearerAuth:
            - APITokenWrite
  /account/tokens/{tokenID}:
    get:
      summary: Get an organizational API token
      description: >-
        Retrieve the given organizational API token for the currently
        authenticated account.
      tags:
        - Token
      security:
        - BearerAuth:
            - GetAPIToken
    patch:
      summary: Partially update an organizational API token
      description: >-
        Partially update the organizational API token of the currently
        authenticated account.
      tags:
        - Token
      security:
        - BearerAuth:
            - UpdateAPIToken
    delete:
      summary: Delete organizational API token
      description: >-
        Remove a given organizational API token from the currently authenticated
        account.
      tags:
        - Token
      security:
        - BearerAuth:
            - DeleteAPIToken
  /account/tokens/{tokenID}/rotate:
    post:
      summary: Rotate an existing organizational API token
      description: >
        Rotates a non-expired organizational API token for the given token ID.

        The current expiry date is extended by the value specified in the
        `lifetime` parameter (if specified).

        The token's permissions remain unchanged.
      tags:
        - Token
      security:
        - BearerAuth:
            - RotateAPIToken
  /accounts:
    get:
      summary: List all Accounts
      description: List accounts that are accessible to the authenticated user.
      tags:
        - Account
      security:
        - BearerAuth:
            - AccountsRead
    post:
      summary: Create an Account
      description: >-
        Create a new account for the authenticated user. The child account will
        inherit the authenticated accounts information.
      tags:
        - Account
      security:
        - BearerAuth:
            - AccountsWrite
  /accounts/{accountID}:
    get:
      summary: Retrieve an Account
      description: Get an Account by its ID. Make sure you have the necessary permissions.
      tags:
        - Account
      security:
        - BearerAuth:
            - AccountsRead
    patch:
      summary: Update an Account
      description: >-
        Update an Account's information. Make sure you have the necessary
        permissions.
      tags:
        - Account
      security:
        - BearerAuth:
            - AccountsWrite
    delete:
      summary: Delete an Account
      tags:
        - Account
      security:
        - BearerAuth:
            - AccountsWrite
  /accounts/{accountID}/parent:
    patch:
      summary: Move account to different parent.
      description: >
        Moves a b2b account (and all its resources) into a target b2b account
        that is accessible to the authenticated user.  

        A b2b account is an account with `kind="b2b"`
      tags:
        - Account
      security:
        - BearerAuth:
            - MoveAccountsWrite
  /accounts/{accountID}/accounts:
    get:
      summary: List all nested Accounts
      description: >-
        List all child accounts of the given account that are accessible to the
        authenticated user.
      tags:
        - Account
      security:
        - BearerAuth:
            - NestedAccountsRead
  /accounts/{accountID}/systems:
    get:
      summary: List Account's Systems
      tags:
        - System
      security:
        - BearerAuth:
            - SystemsRead
    post:
      summary: Assign a System to an Account
      tags:
        - System
      security:
        - BearerAuth:
            - AccountsWrite
    delete:
      summary: Unassign a System from an Account
      tags:
        - System
      security:
        - BearerAuth:
            - AccountsWrite
  /accounts/{accountID}/policies:
    post:
      summary: Assign a Policy Document to an Account
      tags:
        - Policy
      security:
        - BearerAuth:
            - AccountsWrite
  /accounts/{accountID}/documents:
    get:
      summary: Get Account Documents
      description: Lists files with keys that have a specific prefix
      tags:
        - Document
      security:
        - BearerAuth:
            - DocumentsRead
  /accounts/{accountID}/documents/{documentKey}:
    get:
      summary: Get Account Document
      description: Gets a file and downloads a file
      tags:
        - Document
      security:
        - BearerAuth:
            - DocumentsRead
    post:
      summary: Create Account Document
      description: Creates a new file in the s3 bucket
      tags:
        - Document
      security:
        - BearerAuth:
            - DocumentsWrite
    delete:
      summary: Delete Account Document
      description: Delete deletes a file using a given key
      tags:
        - Document
      security:
        - BearerAuth:
            - DocumentsWrite
  /accounts/{accountID}/groups:
    get:
      summary: List all Groups
      tags:
        - Group
      security:
        - BearerAuth:
            - GroupsRead
    post:
      summary: Create a Group
      tags:
        - Group
      security:
        - BearerAuth:
            - GroupsWrite
  /accounts/{accountID}/groups/{groupID}:
    get:
      summary: Retrieve a Group
      tags:
        - Group
      security:
        - BearerAuth:
            - GroupsRead
    patch:
      tags:
        - Group
      summary: Update a Group
      security:
        - BearerAuth:
            - GroupsWrite
    delete:
      tags:
        - Group
      summary: Delete a Group
      security:
        - BearerAuth:
            - GroupsWrite
  /accounts/{accountID}/groups/{groupID}/policies:
    get:
      summary: Get Policy Documents in a Group
      tags:
        - Group
      security:
        - BearerAuth:
            - GroupsRead
            - PoliciesRead
  /accounts/{accountID}/users/{userID}:
    delete:
      summary: Delete User
      description: Delete a user given its ID.
      tags:
        - User
      security:
        - BearerAuth:
            - AccountsUsersWrite
  /accounts/{accountID}/users/{userID}/notifications:
    get:
      summary: List all Notifications
      description: |
        Lists all notification for a user.

        User ID may be explicitly specified as a path parameter,
        otherwise the authenticated user will be used.
      tags:
        - Notification
      security:
        - BearerAuth:
            - AccountsUsersRead
    post:
      summary: Create User Notifications
      description: |
        Creates a notification for a user.

        User ID may be explicitly specified as a path parameter,
        otherwise the authenticated user will be used.
      tags:
        - Notification
      security:
        - BearerAuth:
            - AccountsUsersWrite
  /accounts/{accountID}/users/{userID}/notifications/{notificationID}:
    get:
      summary: Retrieve a Notification
      description: |
        Returns a notification by its ID.
      tags:
        - Notification
      security:
        - BearerAuth:
            - AccountsUsersRead
    put:
      summary: Update Notification
      description: |
        Updates an existing notification.
      tags:
        - Notification
      security:
        - BearerAuth:
            - AccountsUsersWrite
    delete:
      summary: Delete Notification
      description: |
        Deletes an existing notification.
      tags:
        - Notification
      security:
        - BearerAuth:
            - AccountsUsersWrite
  /accounts/{accountID}/users/{userID}/notifications/rules:
    get:
      summary: List all Rules
      description: >
        Lists all rules for the user.


        The user and account may be specified explicitly via path parameters or
        implicitly via the authentication context. Explicitly specified values
        take precedence.
      tags:
        - Notification
      security:
        - BearerAuth:
            - AccountsUsersRead
    post:
      summary: Create a Rule
      description: >
        Creates a new rule.


        The user and account may be specified explicitly via path parameters or
        implicitly via the authentication context. Explicitly specified values
        take precedence.
      tags:
        - Notification
      security:
        - BearerAuth:
            - AccountsUsersWrite
  /accounts/{accountID}/users/{userID}/notifications/rules/{ruleID}:
    get:
      summary: Retrieve a Rule
      description: >
        Returns a rule specified by its ID.


        The user and account may be specified explicitly via path parameters or
        implicitly via the authentication context. Explicitly specified values
        take precedence.
      tags:
        - Notification
      security:
        - BearerAuth:
            - AccountsUsersRead
    put:
      summary: Update a Rule
      description: >
        Updates a rule specified by its ID.


        The user and account may be specified explicitly via path parameters or
        implicitly via the authentication context. Explicitly specified values
        take precedence.
      tags:
        - Notification
      security:
        - BearerAuth:
            - AccountsUsersWrite
    delete:
      summary: Delete a Rule
      description: >
        Deletes a rule specified by its ID.


        The user and account may be specified explicitly via path parameters or
        implicitly via the authentication context. Explicitly specified values
        take precedence.
      tags:
        - Notification
      security:
        - BearerAuth:
            - AccountsUsersWrite
  /accounts/{accountID}/plans:
    get:
      summary: List Charge Plans
      description: |
        Lists all available charge plans.
      tags:
        - Plan
      security:
        - BearerAuth:
            - PlansRead
  /accounts/{accountID}/plans/{planID}:
    post:
      summary: Assign Charge Plan.
      description: |
        Assign charge plan to account.
      tags:
        - Plan
      security:
        - BearerAuth:
            - PlansWrite
    delete:
      summary: Unassign Charge Plan.
      description: |
        Unassign charge plan from account.
      tags:
        - Plan
      security:
        - BearerAuth:
            - PlansWrite
  /accounts/{accountID}/rfidtags/{tagID}:
    get:
      summary: Get RFID Tag
      description: |
        Gets RFID tag for account.
      tags:
        - RFIDTag
      security:
        - BearerAuth:
            - RFIDTagsRead
    patch:
      summary: Update RFID Tag
      description: |
        Updates RFID tag for account.
      tags:
        - RFIDTag
        - Account
      security:
        - BearerAuth:
            - RFIDTagsWrite
    delete:
      summary: Delete RFID Tag
      description: |
        Deletes RFID tag for account.
      tags:
        - RFIDTag
      security:
        - BearerAuth:
            - RFIDTagsWrite
  /accounts/{accountID}/rfidtags/{tagID}/appliances:
    get:
      summary: List Appliances by RFID Tag
      description: |
        Lists all appliances by RFID tag for account.
      tags:
        - RFIDTag
      security:
        - BearerAuth:
            - RFIDTagsRead
  /accounts/{accountID}/rfidtags/{tagID}/appliances/{applianceID}:
    put:
      summary: Assign Tag to Appliances
      description: |
        Assigns a tag to an appliance.
      tags:
        - RFIDTag
      security:
        - BearerAuth:
            - RFIDTagsWrite
    delete:
      summary: Unassign Tag from Appliances
      description: |
        Unassigns a tag from an appliance.
      tags:
        - RFIDTag
      security:
        - BearerAuth:
            - RFIDTagsWrite
  /accounts/{accountID}/parents:
    get:
      summary: List all parent accounts
      description: |
        Lists all parent accounts starting at the passed account until root.
      tags:
        - Account
      security: []
  /accounts/{accountID}/platform-mapping:
    get:
      summary: Get Platform Mapping
      description: Get the platform-related information of the given accountID.
      tags:
        - Platform
      security:
        - BearerAuth: []
  /accounts/{accountID}/bidding-zone:
    get:
      summary: Get bidding zone
      description: |
        Get the electricity market bidding zone of the given accountID.
      tags:
        - Account
      security:
        - BearerAuth:
            - AccountRead
    put:
      summary: Set bidding zone
      description: |
        Set the electricity market bidding zone of the given accountID.
      tags:
        - Account
      security:
        - BearerAuth:
            - AccountWrite
  /account/tariffs:
    get:
      summary: List Energy Tariffs
      deprecated: true
      description: |
        List all available energy tariffs of the account.

        **Deprecated** - Use TariffV2 instead.
      tags:
        - Energy Tariff
      security:
        - BearerAuth:
            - AccountTariffRead
    post:
      summary: Create Energy Tariff
      deprecated: true
      description: |
        Create an energy tariff for the account.

        **Deprecated** - Use TariffV2 instead.
      tags:
        - Energy Tariff
      security:
        - BearerAuth:
            - AccountTariffWrite
  /account/tariffs/{tariffID}:
    get:
      summary: Get Energy Tariff
      deprecated: true
      description: |
        Get the specified energy tariff of the account.

        **Deprecated** - Use TariffV2 instead.
      tags:
        - Energy Tariff
      security:
        - BearerAuth:
            - AccountTariffRead
    patch:
      summary: Update Energy Tariff
      deprecated: true
      description: |
        Update the specified energy tariff of the account.

        **Deprecated** - Use TariffV2 instead.
      tags:
        - Energy Tariff
      security:
        - BearerAuth:
            - AccountTariffWrite
    delete:
      summary: Delete Energy Tariff
      deprecated: true
      description: |
        Delete the specified energy tariff of the account.

        **Deprecated** - Use TariffV2 instead.
      tags:
        - Energy Tariff
      security:
        - BearerAuth:
            - AccountTariffWrite
  /beta/systems:
    get:
      summary: Proxy of the AMT endpoint.
      description: >
        This endpoint proxies the AMT endpoint.

        The request and response are the same, the only difference is the
        endpoint.

        See
        [links](https://backstage.sre.gridx.de/catalog/default/api/system-api/definition#/System/get_applications__application_id__systems)
      tags:
        - Asset
  /clusters:
    get:
      security:
        - BearerAuth:
            - ClustersRead
      summary: Allows to retrieve the list of all available clusters.
      tags:
        - Clusters
    post:
      security:
        - BearerAuth:
            - ClustersWrite
      summary: Create a new cluster.
      tags:
        - Clusters
  /clusters/{clusterID}:
    get:
      security:
        - BearerAuth:
            - ClustersRead
      summary: Allows to retrieve a cluster.
      tags:
        - Clusters
    patch:
      security:
        - BearerAuth:
            - ClustersWrite
      summary: Partially update a cluster.
      tags:
        - Clusters
    put:
      security:
        - BearerAuth:
            - ClustersWrite
      summary: Replace an existing cluster.
      tags:
        - Clusters
    delete:
      security:
        - BearerAuth:
            - ClustersWrite
      summary: Delete an existing cluster.
      tags:
        - Clusters
  /clusters/{clusterID}/members/{memberID}:
    post:
      security:
        - BearerAuth:
            - ClustersWrite
      summary: Assign a member to an existing cluster.
      description: >
        Assign a member to an existing cluster. 

        A cluster member can be either an appliance or another cluster (nested
        cluster).
      tags:
        - Clusters
    delete:
      security:
        - BearerAuth:
            - ClustersWrite
      summary: Unassign a member to an existing cluster.
      tags:
        - Clusters
  /customers:
    get:
      summary: List all Customers
      tags:
        - Customer
      security:
        - BearerAuth:
            - CustomersRead
    post:
      summary: Create Customer
      tags:
        - Customer
      security:
        - BearerAuth:
            - CustomersWrite
  /customers/{accountID}:
    get:
      summary: Get Customer
      description: Get a single customer given its account ID.
      tags:
        - Customer
      security:
        - BearerAuth:
            - CustomersRead
    patch:
      summary: Edit a single customer
      tags:
        - Customer
      security:
        - BearerAuth:
            - CustomersWrite
    delete:
      summary: Delete Customer
      description: Delete a customer given its ID.
      tags:
        - Customer
      security:
        - BearerAuth:
            - CustomersWrite
  /customers/{customerID}/users:
    get:
      summary: List Customer's users
      description: Get a list of all users that belong to this customer.
      tags:
        - Customer
      security:
        - BearerAuth:
            - CustomersUsersRead
    post:
      summary: Create User in Customer
      description: Create a new user for the customer.
      tags:
        - Customer
      security:
        - BearerAuth:
            - CustomersUsersWrite
  /customers/{customerID}/users/{userID}/impersonation:
    post:
      summary: Create Redirect Token
      description: Create a new token for the customer's user.
      tags:
        - Customer
      security:
        - BearerAuth:
            - CustomersUsersImpersonationWrite
  /customers/{accountID}/systems:
    get:
      summary: List Systems of a Account
      description: List Systems that belong to a Account of a Customer
      tags:
        - System
        - Customer
      security:
        - BearerAuth:
            - SystemsRead
    post:
      summary: Adds a System to an Account
      description: Adds a new System to an Account of a Customer
      tags:
        - System
        - Customer
      security:
        - BearerAuth:
            - SystemsWrite
  /customers/{accountID}/users/{userID}/logins:
    get:
      summary: List Login Events of a User
      description: returns a list of authentication events of the authenticated user
      tags:
        - Customer
      security:
        - BearerAuth:
            - CustomersUsersRead
  /systems/{systemID}/gateways/{gatewayID}/import-power-limit:
    get:
      summary: Retrieve gateway's current import power limit.
      tags:
        - Import Power Limit
      security:
        - BearerAuth:
            - SystemsRead
    put:
      summary: Set gateway's import power limit.
      tags:
        - Import Power Limit
      security:
        - BearerAuth:
            - SystemsWrite
    delete:
      summary: Delete gateway's import power limit.
      tags:
        - Import Power Limit
      security:
        - BearerAuth:
            - SystemsWrite
  /systems/{systemID}/gateways/{gatewayID}/import-power-limit/historical:
    get:
      summary: Get gateway's historical import power limits.
      tags:
        - Import Power Limit
      security:
        - BearerAuth:
            - SystemsRead
  /systems:
    get:
      summary: List all Systems
      description: List systems that are accessible to the authenticated user.
      tags:
        - System
      security:
        - BearerAuth:
            - SystemsRead
    post:
      summary: Create a System
      description: Creates a System.
      tags:
        - System
      security:
        - BearerAuth:
            - SystemsWrite
  /systems/{systemID}:
    get:
      summary: Retrieve a System
      description: Retrieves the details of an existing system.
      tags:
        - System
      security:
        - BearerAuth:
            - SystemsRead
    patch:
      summary: Update a System
      description: >
        Updates the specific system by setting the values of the body
        parameters.


        Any parameters not provided will be left unchanged.
      tags:
        - System
      security:
        - BearerAuth:
            - SystemsWrite
    delete:
      summary: Delete a System
      description: >
        Deletes a system.


        **Important**: The system must not have any attached Gateway. Reset any
        attached Gateway first by creating a *reset job*.
      tags:
        - System
      security:
        - BearerAuth:
            - SystemsWrite
  /gateways:
    get:
      summary: List all Gateways
      description: List gateways that are accessible to the authenticated user.
      tags:
        - Gateway
      security:
        - BearerAuth:
            - GatewaysRead
  /gateways/{gatewayID}:
    get:
      summary: Retrieve a Gateway
      description: Retrieves the details of an existing gateway.
      tags:
        - Gateway
      security:
        - BearerAuth:
            - GatewaysRead
    patch:
      summary: Update a Gateway
      description: >
        Updates the specific gateway by setting the values of the body
        parameters.


        Any parameters not provided will be left unchanged.
      tags:
        - Gateway
      security:
        - BearerAuth:
            - GatewaysWrite
    delete:
      summary: Delete a Gateway
      description: Deletes a Gateway.
      tags:
        - Gateway
      security:
        - BearerAuth:
            - GatewaysWrite
  /systems/{systemID}/gateways:
    post:
      summary: Create a System's Gateway
      description: Creates a gateway.
      tags:
        - Gateway
      security:
        - BearerAuth:
            - GatewayWrite
  /gateways/{gatewayID}/scans:
    get:
      summary: List Gateway's Scans
      description: >
        List of scans for the given gateway and the given interval.


        If no interval is specified, the entire period is considered and all
        scans are listed.
      tags:
        - Scan
      security:
        - BearerAuth:
            - ScansRead
  /gateways/{gatewayID}/jobs:
    get:
      summary: List Gateway's Jobs
      description: |
        List jobs that belong to the given gateway.
      tags:
        - Job
      security:
        - BearerAuth:
            - JobsRead
  /gateways/{gatewayID}/jobs/{jobIDOrType}:
    get:
      summary: Get a Job
      description: >
        Gets a particular job that belongs to the given gateway. In this case,
        the path parameter should be a job ID.
      tags:
        - Job
      security:
        - BearerAuth:
            - JobsRead
    post:
      summary: Create a job with a given type
      description: >
        Creates a job with the given type for the given gateway, only if a job
        with that type doesn't already exist.

        In this case, the path parameter should be a job type. Please note that
        the job type is case-sensitive.

          * `SCAN`: Once this job is triggered, the gridBox will look for connected appliances and update the list accordingly.

          * `RESET`: This type of job resets gridBox to default and removes it from previously configured system.

          * `RESTART`: Once this job is triggered, the gridBox will restart.

        *Job execution is asynchronous and does not guarantee immediate
        execution.*
      tags:
        - Job
      security:
        - BearerAuth:
            - JobsWrite
    delete:
      summary: Cancel a particular job
      description: >
        Cancels a particular job from the given gateway. In this case, the path
        parameter should be a job ID.
      tags:
        - Job
      security:
        - BearerAuth:
            - JobsWrite
  /gateways/{gatewayID}/appliances:
    get:
      summary: List Gateway's Appliances
      description: >
        Lists appliances that belong to the given gateway.


        Children appliances, e.g. those of hybrid inverters, are not included by
        default.

        To include them, `listAll` parameter must be set to `true`.
      tags:
        - Appliance
      security:
        - BearerAuth:
            - AppliancesRead
    post:
      summary: Create an Appliance
      description: >
        This endpoint can be used by third parties to create external appliances
        that are not managed by the gridBox itself.
      tags:
        - Appliance
      security:
        - BearerAuth:
            - AppliancesWrite
  /gateways/{gatewayID}/appliances/{applianceID}:
    get:
      summary: Retrieve an Appliance
      description: Retrieves the details of an existing appliance.
      tags:
        - Appliance
      security:
        - BearerAuth:
            - AppliancesRead
    patch:
      summary: Update an Appliance
      description: >
        Updates the specific appliance by setting the values of the body
        parameters. 


        Any parameters not provided will be left unchanged.
      tags:
        - Appliance
      security:
        - BearerAuth:
            - AppliancesWrite
    delete:
      summary: Delete an Appliance
      description: Deletes an appliances.
      tags:
        - Appliance
      security:
        - BearerAuth:
            - AppliancesWrite
  /gateways/{gatewayID}/appliances/{applianceID}/status:
    get:
      summary: Retrieve appliance hardware statuses
      description: >
        Returns appliance hardware statuses for the given interval.


        Only returns multiple statuses when state changes during the given
        interval. If, for example, the state stayed the same for the whole
        interval,

        only one status will be returned.


        Works only for **inverters** currently.
      tags:
        - Appliance
      security:
        - BearerAuth:
            - AppliancesRead
  /gateways/{gatewayID}/appliances/{applianceID}/ev/configuration:
    get:
      summary: Retrieve an EV configuration
      description: Returns an EV charging station's configuration.
      tags:
        - EV Configuration
      security:
        - BearerAuth:
            - AppliancesEVConfigurationRead
    post:
      summary: Create an EV Configuration
      description: >
        Creates an EV charging station's configuration if no configuration is
        present.
      tags:
        - EV Configuration
      security:
        - BearerAuth:
            - AppliancesEVConfigurationWrite
    patch:
      summary: Update an EV configuration
      description: >-
        Updates the specified appliance's EV charging station configuration by
        setting the body parameters.
      tags:
        - EV Configuration
      security:
        - BearerAuth:
            - AppliancesEVConfigurationWrite
    delete:
      summary: Delete an EV configuration
      description: Deletes an EV charging Station configuration.
      tags:
        - EV Configuration
      security:
        - BearerAuth:
            - AppliancesEVConfigurationWrite
  /gateways/{gatewayID}/appliances/{applianceID}/battery/settings:
    get:
      summary: Retrieve Battery Control Settings
      description: Returns battery control Settings
      deprecated: true
      tags:
        - Battery Control Command
      security:
        - BearerAuth:
            - AppliancesBatteryControlSettingsRead
    post:
      summary: Create Battery Control Settings
      deprecated: true
      tags:
        - Battery Control Command
      security:
        - BearerAuth:
            - AppliancesBatteryControlSettingsWrite
    patch:
      summary: Update Battery Control Settings
      deprecated: true
      description: >-
        Updates the specific appliance's battery control settings by setting the
        values of the body parameter.
      tags:
        - Battery Control Command
      security:
        - BearerAuth:
            - AppliancesBatteryControlSettingsWrite
    delete:
      summary: Delete Battery Control Settings
      deprecated: true
      description: Deletes appliance's battery control settings.
      tags:
        - Battery Control Command
      security:
        - BearerAuth:
            - AppliancesBatteryControlSettingsWrite
  /systems/{systemID}/ev-profiles:
    get:
      summary: List available EV profiles
      description: Lists EV profiles that belong the the specified system.
      tags:
        - EV Profile
      security:
        - BearerAuth:
            - EVProfilesRead
    post:
      summary: Create a new EV profile
      description: Creates an EV profile.
      tags:
        - EV Profile
      security:
        - BearerAuth:
            - EVProfilesWrite
  /systems/{systemID}/ev-profiles/{evProfileID}:
    get:
      summary: Retrieve an EV profile
      description: Retrieve an EV profile that belong the the specified system.
      tags:
        - EV Profile
      security:
        - BearerAuth:
            - EVProfilesRead
    patch:
      summary: Update an EV profile
      description: Update an EV profile that belong the the specified system.
      tags:
        - EV Profile
      security:
        - BearerAuth:
            - EVProfilesWrite
    delete:
      summary: Delete an EV profile
      description: Deletes an EV profile that belongs to the specified system.
      tags:
        - EV Profile
      security:
        - BearerAuth:
            - EVProfilesWrite
  /systems/{systemID}/evcharging-schedules:
    get:
      summary: List a System's EV charging schedules.
      description: >
        Lists EV charging schedules that belong to the specified system.


        It only contains the currently active schedules and schedules to be
        active in the

        next 24 hours.
      tags:
        - EV Charging Schedule
      security:
        - BearerAuth:
            - SchedulesRead
    post:
      summary: Create an EV charging schedule
      description: Creates a system's EV charging schedule.
      tags:
        - EV Charging Schedule
      security:
        - BearerAuth:
            - SchedulesWrite
  /systems/{systemID}/evcharging-schedules/{scheduleID}:
    get:
      summary: Retrieve an EV charging schedule
      description: Retrieves the details of an existing EV charging station schedule.
      tags:
        - EV Charging Schedule
      security:
        - BearerAuth:
            - SchedulesRead
    patch:
      summary: Update an EV charging schedule
      description: >-
        Updates the specified systems EV charging schedule by setting the body
        parameters.
      tags:
        - EV Charging Schedule
      security:
        - BearerAuth:
            - SchedulesWrite
    delete:
      summary: Delete an EV charging schedule
      description: Deletes an EV charging schedule.
      tags:
        - EV Charging Schedule
      security:
        - BearerAuth:
            - SchedulesWrite
  /systems/{systemID}/power-limit-schedules:
    get:
      summary: List a Systems power limit schedules.
      description: |
        List all power limit schedules of the system.
      tags:
        - Power Limit Schedule
    post:
      summary: Create a power limit schedule
      description: Creates a power limit schedule for this system.
      tags:
        - Power Limit Schedule
  /systems/{systemID}/power-limit-schedules/{scheduleID}:
    get:
      summary: Retrieve a power limit schedule
      description: Retrieves the details of an existing power limit schedule.
      tags:
        - Power Limit Schedule
    patch:
      summary: Update a power limit schedule
      description: Updates the specified power limit schedule.
      tags:
        - Power Limit Schedule
    delete:
      summary: Delete a power limit schedule
      description: Deletes a power limit schedule.
      tags:
        - Power Limit Schedule
  /systems/{systemID}/power-limit-schedules-intervals:
    get:
      summary: List applied power limits intervals
      description: >
        Returns a list of scheduled power limit intervals.


        Intervals in the past are fixed and will never change. 

        Intervals in the future can change if the underlying schedule is
        changed.
      tags:
        - Power Limit Schedule
  /systems/{systemID}/capacity-tariff:
    get:
      summary: Get the capacity tariff information.
      tags:
        - Capacity Tariff
      security:
        - BearerAuth:
            - CapacityTariffRead
    post:
      summary: Create the user limit, price and enable or disable the limit.
      tags:
        - Capacity Tariff
      security:
        - BearerAuth:
            - CapacityTariffWrite
    patch:
      summary: Update the user limit, price and enable or disable the limit.
      tags:
        - Capacity Tariff
      security:
        - BearerAuth:
            - CapacityTariffWrite
    delete:
      summary: Deletes the Capacity Tariff.
      tags:
        - Capacity Tariff
      security:
        - BearerAuth:
            - CapacityTariffWrite
  /systems/{systemID}/capacity-tariff/recommendation:
    post:
      summary: Create the recommended capacity tariff limit.
      description: >-
        When updating the recommended limit it is effectively if the userLimit
        is disabled.
      tags:
        - Capacity Tariff
      security:
        - BearerAuth:
            - CapacityTariffRecommendationWrite
    delete:
      summary: Delete capacity tariff recommendation
      description: Removes the recommended value from the capacity tariff.
      tags:
        - Capacity Tariff
      security:
        - BearerAuth:
            - CapacityTariffRecommendationWrite
  /systems/{systemID}/capacity-tariff/peak-power:
    post:
      summary: Set the capacity tariff peak-power.
      description: >-
        When setting the peak-power it becomes the new `effectiveLimit` if it is
        higher than the user and recommended limit.
      tags:
        - Capacity Tariff
      security:
        - BearerAuth:
            - CapacityTariffPeakPowerWrite
    delete:
      summary: Delete capacity tariff peak-power
      description: >-
        After deleting the peak-power limit, the new `effectiveLimit` would be
        the user's (if enabled) or the recommended limit.
      tags:
        - Capacity Tariff
      security:
        - BearerAuth: []
  /systems/{systemID}/savings/{saving}:
    get:
      summary: Retrieve saving of a system
      description: >
        Retrieves a specific saving of a system obtained through various
        optimizations.


        Which savings are available for a system is specified in the systems
        metadata. Requesting unavailable savings will always return a value of
        0.


        The saving is **cached** and can be refreshed by specifying the
        corresponding URL parameter.
      tags:
        - System
      security:
        - BearerAuth:
            - SystemsRead
  /systems/{systemID}/tariff:
    get:
      summary: Retrieve the tariff v2 of a system
      description: |
        Retrieves the tariff v2 of the system. 
      tags:
        - TariffV2
      security:
        - BearerAuth: []
    post:
      summary: Set the tariff v2 of a system
      description: >
        Sets the tariff v2 of the system. 


        See the response bodies description which fields have to be set for
        which `feedinType`/`offtakeType`.
      tags:
        - TariffV2
      security:
        - BearerAuth: []
    patch:
      summary: Update the tariff v2 of a system
      description: >
        Updates the tariff v2 of the system.


        See the response bodies description which fields have to be set for
        which `feedinType`/`offtakeType`.
      tags:
        - TariffV2
      security:
        - BearerAuth:
            - TariffWrite
  /systems/{systemID}/tariff/prices:
    get:
      summary: Retrieve the tariff end prices of a system
      description: >
        Retrieves the end-price tariff for the system in the specified
        resolution (15-minute by default if not specified).

        The end-price is the price the customer is billed for (for market data
        tariffs for example after offset, VAT and provider fee are applied).


        Depending on the tariff settings, the tariff data might have been
        directly posted through the API, originate from market data 

        or is extrapolated from static data.


        If the resolution of the underlying data doesn't correspond to the
        requested resolution the data will be up- or down-sampled.

        For example the market prices used by market data tariffs have a 1 hour
        resolution. If you request 15min resolution you will

        get 4 equal periods per hour. If you request daily resolution, the
        average prices of 24 hourly periods will be returned per period.  


        If there are missing price periods over the requested interval (which
        may happen for `EXTERNAL` tariffs), the end-price tariff will start
        after the last period gap, aligned with the requested resolution.

        That is, if the requested interval for a given day is from 00:00 to
        12:00 and no prices were sent from at 02:15 to 03:45, the first period
        returned will be from 03:45 to 04:00 for a 15-min resolution or from
        04:00 to 05:00 for an hourly resolution.


        Once calculated the prices won't change anymore for the requested
        period.

        Even if the tariff is reconfigured the returned price will stay the
        same.

        This is due to the fact that historical prices can not be changed
        anymore. 

        Changes in the tariff will only have an effect in the future.


        The returned currency is determined by the currency of the underlying
        tariff if not specified otherwise.
      tags:
        - TariffV2
      security:
        - BearerAuth: []
    post:
      summary: Set tariff end prices of a system
      description: >
        Sets the tariff end prices for **external tariffs**.


        The sent price periods have a few restrictions:

        - They must have a 15 minute resolution.

        - They must not have gaps for current and future prices (gaps in the
        past are allowed).


        The prices can be sent in all supported currencies and will be converted
        by the `GET /tariff/prices` endpoint accordingly.


        You don't have to send your prices in all the currencies you want to
        support.

        Internally they always will be converted to Euro, therefore sending the
        same price periods in different currencies will overwrite

        the previously sent price periods. 
      tags:
        - TariffV2
      security:
        - BearerAuth: []
  /systems/{systemID}/timeofuse/decisions:
    get:
      summary: Get time of use optimization decisions of a system.
      description: >
        Get optimization decisions and associated metrics for a system with
        `system_id`,

        within given time interval. Note that decisions may not always cover the
        complete time interval.

        Only decisions with `start_at` in the past are returned.

        The maximum time interval that can be requested is 48 hours.
      tags:
        - TimeOfUse
      security:
        - BearerAuth: []
  /systems/{systemID}/timeofuse/settings:
    get:
      summary: Get time of use optimization settings of a system.
      description: Get time of use optimization settings of a system.
      tags:
        - TimeOfUse
      security:
        - BearerAuth: []
    put:
      summary: Set time of use optimization settings for a system.
      description: Set time of use optimization settings for a system.
      tags:
        - TimeOfUse
      security:
        - BearerAuth: []
    patch:
      summary: Update time of use optimization settings for a system.
      description: Update time of use optimization settings for a system.
      tags:
        - TimeOfUse
      security:
        - BearerAuth: []
  /systems/{systemID}/timeofuse/forecasts/meter:
    get:
      summary: Get the Time-of-Use forecasts for the grid connection point.
      description: >
        The Time-of-Use (ToU) optimization runs on a given resolution of 15
        minutes.

        For each time segment, i.e. `[10:00, 10:15]` it publishes a series of
        forecasts for

        the grid connection point associated with a system with `systemID`.


        This endpoint requires to specify a time window called `interval` for
        which the forecasts are returned.

        For example `[2021-01-01T02:07:14Z, 2021-01-02T02:07:14Z]`.

        If no interval is provided it is assumed to be `[00:00:00 today,
        00:00:00 in two days]`.

        The maximum size of this interval is 48h.


        This endpoint returns the forecasts **in the selected time window**.

        Please note that the forecasts might not cover the whole time window.

        In this case the largest possible subset is returned.

        If no forecast is available, an empty list is returned.
      tags:
        - TimeOfUse
      security:
        - BearerAuth: []
  /systems/{systemID}/timeofuse/forecasts/meter/last-updated:
    get:
      summary: >-
        Get the last updated timestamp for the Time-of-Use forecasts for the
        grid connection point.
      description: >
        The Time-of-Use (ToU) optimization runs on a given resolution of 15
        minutes.

        For each time segment, i.e. `[10:00, 10:15]` it publishes a series of
        forecasts for

        the grid connection point associated with a system with `systemID`.


        This endpoint requires to specify a time window called `interval` for
        which the forecasts are returned.

        For example `[2021-01-01T02:07:14Z, 2021-01-02T02:07:14Z]`.

        If no interval is provided it is assumed to be `[00:00:00 today,
        00:00:00 in two days]`.

        The maximum size of this interval is 48h.


        This endpoint returns the last timestamp RFC3339 format when the
        forecasts **in the selected time window**

        were updated.
      tags:
        - TimeOfUse
      security:
        - BearerAuth: []
  /systems/{systemID}/timeofuse/status:
    get:
      summary: Get the historical status of the Time-of-Use service.
      description: >-
        The Time-of-Use (ToU) optimization runs on a given resolution of 15
        minutes.

        For each time segment, i.e. `[10:00, 10:15]` it publishes an operational
        status

        associated with a system with `systemID`.


        This endpoint requires to specify a time window called `interval` for
        which the status data are returned.

        For example `[2021-01-01T02:07:14Z, 2021-01-02T02:07:14Z]`.

        If no interval is provided it is assumed to be `[now - 48h, now]`.

        The maximum size of this interval is 48h.

        Please note that the statuses might not cover the whole time window.
      tags:
        - TimeOfUse
      security:
        - BearerAuth: []
  /systems/{systemID}/timeofuse/status/current:
    get:
      summary: Get the last known status of the Time-of-Use service.
      description: >-
        The Time-of-Use (ToU) optimization runs on a given resolution of 15
        minutes.

        For each time segment, i.e. `[10:00, 10:15]` it publishes an operational
        status for

        associated with a system with `systemID`.


        This endpoint provides the last known, or current, status of the
        Time-of-Use runs.
      tags:
        - TimeOfUse
      security:
        - BearerAuth: []
  /systems/{systemID}/timeofuse/readiness:
    get:
      summary: Evaluate whether the system is ready for enabling Time-of-Use.
      description: >-
        A series of operational prerequisites are required before enabling
        Time-of-Use (ToU) for a system.

        The checks are done in order to evaluate the system's "readiness" for
        ToU.

        In principal, checks pertaining to appliances used, price data used, as
        well as some system metadata are performed.
      tags:
        - TimeOfUse
      security:
        - BearerAuth: []
  /systems/{systemID}/grid-signals:
    get:
      summary: Get system grid signal capabilities.
      description: >
        Gets information about the system's capabilities to deal with grid
        signals. 
      tags:
        - GridSignals
      security:
        - BearerAuth: []
    patch:
      summary: Update system grid signal capabilities.
      description: >
        Updates information about the system's capabilities to deal with grid
        signals. 
      tags:
        - GridSignals
      security:
        - BearerAuth: []
  /systems/{systemID}/ems-capabilities:
    get:
      summary: Get system EMS capabilities.
      description: >
        __WARN: This API is only for internal usage!__


        Gets information about the system's EMS capabilities. The latest
        reported list of capabilities is returned.


        Empty response means no capabilities were reported by EMS so far. Full
        list of supported capabilities is maintained by gridBox team.
      tags:
        - EMS
      security:
        - BearerAuth: []
  /systems/{systemID}/live:
    get:
      summary: Retrieve System's Live Measurement.
      description: Retrieves a system's latest aggregated measurement.
      tags:
        - System
      security:
        - BearerAuth:
            - SystemMeasurementsRead
  /systems/{systemID}/historical:
    get:
      summary: Historical Measurements for Systems
      description: |
        Lists aggregated measurements of a system over a period of time.

        System measurements are the result of incorporating measurements from 
        all appliances that are part of a system. This allows computing e.g. 
        overall consumption adding producers (e.g. PV) and subtracting consumers
        (e.g. EV charging stations). This aggregation is performed in various 
        resolutions to suit different use cases. See the 'resolution' parameter
        for a list of options.

        Depending on the resolution parameter, the response contains either
        power or energy measurements (unless otherwise documented):
        - **power** (unit: W): `15m`, `1h`
        - **energy** (unit: Wh): `1d`, `1w`, `1M`, `1y`

        Measurements are "aligned" differently whether they contain energy or
        power measurements:
        - For power values the data point is written after the aggregated time 
          span. For the interval 2018-04-01T00:00:00Z/2018-04-02T00:00:00Z
          with resolution 15m the first observation will be recorded at 
          2018-04-01T00:15:00Z
        - For energy values the observation is stored at the beginning of 
          the aggregated time span. For the interval 
          2018-04-01T00:00:00Z/2018-04-05T00:00:00Z and resolution 1d the first 
          observation will be recorded at 2018-04-01T00:00:00Z

        The `total` object of the response contains an aggregation of the 
        individual data points over time and therefore is an energy value.
        The `total.measuredAt` field is an interval containing all data points 
        in the requested interval.

        In order to reduce the duration of the endpoint, the gridX API imposes 
        limitations on the interval for a given resolution:

        | Resolution | Limit                   |
        |------------|-------------------------|
        | 15m        | intervals up to 1 day   |
        | 1h         | intervals up to 1 week  |
        | 1d         | intervals up to 1 month |
        | 1w         | intervals up to 1 month |
        | 1M         | intervals up to 5 years |
        | 1y         | no limit                |
      tags:
        - System
      security:
        - BearerAuth:
            - SystemMeasurementsRead
  /gateways/{gatewayID}/appliances/{applianceID}/measurements/appliance:
    get:
      summary: List Appliance's Raw Measurements
      description: |
        Lists raw measurements of an appliance over a period of time.

        The provided `interval` must not span more than 24 hours.

        The resolution cannot be controlled. The granularity at which we store
        measurements varies from appliance to appliance, firmware and 
        configuration.
      tags:
        - Appliance
      security:
        - BearerAuth:
            - ApplianceMeasurementsRead
    post:
      summary: Write Appliance Measurements
      tags:
        - Appliance
      security:
        - BearerAuth:
            - ApplianceMeasurementsWrite
  /gateways/{gatewayID}/appliances/{applianceID}/measurements:
    get:
      summary: List Appliance's Combined Measurements
      description: >
        Lists combinations of appliance measurements and energy management 

        measurements. 


        This endpoints adds a "convenience" method for fetching raw
        measurements 

        and energy management measurements together, by combining them into a 

        single measurement object. 


        It is usually used to inspect the EMS behavior in correspondence to raw 

        values reported by the appliance. 


        The requested `interval` must not span more than 24 hours.
      tags:
        - Appliance
      security:
        - BearerAuth:
            - ApplianceMeasurementsRead
  /gateways/{gatewayID}/appliances/{applianceID}/measurements/energymanagement:
    get:
      summary: List Appliance's Energy Management Measurements
      description: >
        Lists energy management measurements of an appliance over a period of
        time.

        Data points returned are emitted directly by the Energy Management

        System (EMS), therefore the resolution cannot be controlled. The 

        granularity at which we store measurements depends on the EMS mode and 

        configuration. 

        The provided `interval` must not span more than 24 hours.
      tags:
        - Appliance
      security:
        - BearerAuth:
            - ApplianceMeasurementsRead
  /clusters/{clusterID}/live:
    get:
      summary: Retrieve Cluster's Live Measurement.
      description: Retrieves a cluster's latest aggregated measurement.
      tags:
        - Cluster
      security:
        - BearerAuth:
            - SystemMeasurementsRead
  /clusters/{clusterID}/historical:
    get:
      summary: Historical Measurements for cluster
      description: |
        Lists aggregated measurements of a cluster over a period of time.

        Cluster measurements are the result of incorporating measurements from 
        all appliances that are part of a cluster. This allows computing e.g. 
        overall consumption adding producers (e.g. PV) and subtracting consumers
        (e.g. EV charging stations). This aggregation is performed in various 
        resolutions to suit different use cases. See the 'resolution' parameter
        for a list of options.

        Depending on the resolution parameter, the response contains either
        power or energy measurements (unless otherwise documented):
        - **power** (unit: W): `10m`, `15m`, `1h`
        - **energy** (unit: Wh): `1d`, `1w`, `1M`, `1y`

        **Note**: Fetching historical measurements with 10m resolution works
        only for intervals **before** 2021-06-15T00:00:00Z.

        Measurements are "aligned" differently whether they contain energy or
        power measurements:
        - For power values the data point is written after the aggregated time 
          span. For the interval 2018-04-01T00:00:00Z/2018-04-02T00:00:00Z
          with resolution 15m the first observation will be recorded at 
          2018-04-01T00:15:00Z
        - For energy values the observation is stored at the beginning of 
          the aggregated time span. For the interval 
          2018-04-01T00:00:00Z/2018-04-05T00:00:00Z and resolution 1h the first 
          observation will be recorded at 2018-04-01T00:00:00Z
      tags:
        - Cluster
      security:
        - BearerAuth: []
  /policies:
    get:
      summary: List Policy Documents
      description: Lists all ever created policy documents
      tags:
        - Policy
      security:
        - BearerAuth:
            - PoliciesRead
    post:
      summary: Create Policy Document
      description: Creates a new policy document.
      tags:
        - Policy
      security:
        - BearerAuth:
            - PoliciesWrite
  /policies/{policyID}:
    get:
      summary: Get Policy Document
      description: Gets policy document based on its ID.
      tags:
        - Policy
      security:
        - BearerAuth:
            - PoliciesRead
    patch:
      summary: Update Policy Document
      description: Updates a policy document.
      tags:
        - Policy
      security:
        - BearerAuth:
            - PoliciesWrite
    delete:
      summary: Delete Policy Document
      description: Deletes a policy document.
      tags:
        - Policy
      security:
        - BearerAuth:
            - PoliciesWrite
  /policies/{policyID}/statements/{statementID}:
    delete:
      summary: Unassign Policy Statement from Document
      description: Un-assigns a policy statement from a policy document
      tags:
        - Policy
      security:
        - BearerAuth:
            - PoliciesWrite
  /policies/{policyID}/groups:
    post:
      summary: Assign Policy Document to Group
      tags:
        - Policy
        - Group
      security:
        - BearerAuth:
            - GroupsWrite
  /policies/{policyID}/groups/{groupID}:
    delete:
      summary: Unassign Policy Document from Group
      tags:
        - Policy
        - Group
      security:
        - BearerAuth:
            - GroupsWrite
  /product-functionalities:
    post:
      summary: Create Product Functionality
      description: Creates a new product functionality.
      tags:
        - Product Functionality
      security:
        - BearerAuth: []
    get:
      summary: List Product Functionalities
      description: Lists all product functionalities.
      tags:
        - Product Functionality
      security:
        - BearerAuth: []
  /product-functionalities/{functionalityID}:
    get:
      summary: Get a Product Functionality
      description: Lists all product functionalities.
      tags:
        - Product Functionality
      security:
        - BearerAuth: []
    delete:
      summary: Delete Product Functionality
      description: Delete a product functionality.
      tags:
        - Product Functionality
      security:
        - BearerAuth: []
  /accounts/{accountID}/product-options:
    post:
      summary: Create Product Option
      description: Creates a new product option.
      tags:
        - Product Option
      security:
        - BearerAuth: []
    get:
      summary: List Product Options
      description: >
        Lists all product options created by the given account and its children.


        Product options returned by this endpoint are not necessarily assignable
        to all systems assigned to the given account. 
      tags:
        - Product Option
      security:
        - BearerAuth: []
  /accounts/{accountID}/product-options/{optionID}:
    patch:
      summary: Update a Product Option
      description: Updates a product option.
      tags:
        - Product Option
      security:
        - BearerAuth: []
    delete:
      summary: Delete Product Option
      description: Delete a product option.
      tags:
        - Product Option
      security:
        - BearerAuth: []
  /spine/devices:
    get:
      summary: List all connected devices
      description: |
        List devices that are accessible to the authenticated account. 
        The response contains devices grouped by their provider.
      tags:
        - Devices
      security:
        - BearerAuth:
            - SPINEDevicesRead
  /spine/devices/{deviceID}/powersequences/{sequenceID}:
    patch:
      summary: Change a specific power sequence for a specific device.
      description: >
        A PATCH may be performed on startTime and endTime of an existing power
        sequence. 

        If only one parameter is specified, the other is calculated from the
        accumulated duration of all power time slots for this sequence.

        A device binding is needed before changing the power sequence. If a
        binding doesn't exist, it is first created and then the power sequence
        is updated.
      tags:
        - Power Sequence
      security:
        - BearerAuth:
            - SPINEDevicesWrite
  /user:
    get:
      summary: Retrieve the authenticated User
      description: Retrieves the details of the authenticated user.
      tags:
        - User
      security:
        - BearerAuth:
            - ReadUser
    patch:
      summary: Update the authenticated User
      description: >
        Updates the authenticated user by setting the values of the body
        parameters.

        Any parameters not provided will be left unchanged.
      tags:
        - User
      security:
        - BearerAuth:
            - WriteUser
  /user/logins:
    get:
      summary: Retrieve the authenticated user's login history
      description: Retrieves the history of the last user logins.
      tags:
        - User
      security:
        - BearerAuth:
            - ListLogins
  /user/policies:
    get:
      summary: List Policy Documents attached to the authenticated User
      tags:
        - User
      security:
        - BearerAuth:
            - PoliciesRead
  /user/stars/systems:
    get:
      summary: List all starred Systems
      description: List starred systems of the authenticated user.
      tags:
        - Star
      security:
        - BearerAuth:
            - ListStarredSystems
  /user/stars/systems/{systemID}:
    put:
      summary: Star a System
      description: Marks a system as favorite by starring it.
      tags:
        - Star
      security:
        - BearerAuth:
            - StarSystem
    delete:
      summary: Unstar a System
      description: Removes a system from favorites by unstarring it.
      tags:
        - Star
      security:
        - BearerAuth:
            - UnstarSystem
  /user/stars/accounts:
    get:
      summary: List all starred Accounts
      description: Lists all starred accounts for the authenticated user.
      tags:
        - Star
      security:
        - BearerAuth:
            - ListAccounts
  /user/stars/accounts/{accountID}:
    put:
      summary: Star an Account
      description: Marks an account as favorite by starring it.
      tags:
        - Star
      security:
        - BearerAuth:
            - StarAccount
    delete:
      summary: Unstar an Account
      description: Removes a given account from favorites by unstarring it.
      tags:
        - Star
      security:
        - BearerAuth:
            - UnstarAccount
  /user/accounts:
    get:
      summary: Get user accounts
      description: Returns a list of accounts the authenticated user can switch to.
      tags:
        - Account
        - User
      security:
        - BearerAuth:
            - ListAccounts
  /user/notifications:
    get:
      summary: List Notifications
      description: Lists dashboard notifications the authenticated user.
      tags:
        - Notification
      security:
        - BearerAuth:
            - ListNotifications
  /user/notifications/{notificationID}:
    get:
      summary: Retrieve a Notification
      description: Retrieves specific dashboard notification of the authenticated user.
      tags:
        - Notification
      security:
        - BearerAuth:
            - GetNotification
    patch:
      summary: Update a Notification
      description: Updates a dashboard notification of the authenticated user.
      tags:
        - Notification
      security:
        - BearerAuth: []
  /user/tokens:
    get:
      summary: List all Tokens
      description: Lists all the API tokens for the authenticated user.
      tags:
        - Token
      security:
        - BearerAuth:
            - GetAPITokens
    post:
      summary: Create a Token
      tags:
        - Token
      security:
        - BearerAuth:
            - APITokenWrite
  /user/tokens/{tokenID}:
    get:
      summary: Retrieve a Token
      description: Retrieves the given API token for the authenticated user.
      tags:
        - Token
      security:
        - BearerAuth:
            - GetAPIToken
    patch:
      summary: Update a Token
      description: |
        Updates the specific token by setting the values of the body parameters.
        Any parameters not provided will be left unchanged. 
      tags:
        - Token
      security:
        - BearerAuth:
            - UpdateAPIToken
    delete:
      summary: Delete a Token
      description: Removes a given token from the authenticated user.
      tags:
        - Token
      security:
        - BearerAuth:
            - DeleteAPIToken
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    BearerAuthentication:
      type: http
      scheme: bearer